; <?php exit; ?> DO NOT REMOVE THIS LINE
; file automatically generated or modified by Piwik; you can manually override the default values in global.ini.php by redefining them in this file.
[superuser]
login = "root"
password = "31c9e7fe7ec95abae145cbc0ec354d9c"
email = "root@prayer4work.com"
salt = "574058fd5ba8033bae962d79287cbac1"

[database]
host = "localhost"
username = "wordpress"
password = "wordpress"
dbname = "wordpress"
tables_prefix = "piwik_"
adapter = "PDO_MYSQL"
port = 3306
charset = "utf8"

[PluginsInstalled]
PluginsInstalled[] = "Login"
PluginsInstalled[] = "CoreAdminHome"
PluginsInstalled[] = "UsersManager"
PluginsInstalled[] = "SitesManager"
PluginsInstalled[] = "Installation"
PluginsInstalled[] = "CorePluginsAdmin"
PluginsInstalled[] = "CoreHome"
PluginsInstalled[] = "API"
PluginsInstalled[] = "Widgetize"
PluginsInstalled[] = "LanguagesManager"
PluginsInstalled[] = "Actions"
PluginsInstalled[] = "Dashboard"
PluginsInstalled[] = "MultiSites"
PluginsInstalled[] = "Referers"
PluginsInstalled[] = "UserSettings"
PluginsInstalled[] = "Goals"
PluginsInstalled[] = "SEO"
PluginsInstalled[] = "UserCountry"
PluginsInstalled[] = "VisitsSummary"
PluginsInstalled[] = "VisitFrequency"
PluginsInstalled[] = "VisitTime"
PluginsInstalled[] = "VisitorInterest"
PluginsInstalled[] = "ExampleAPI"
PluginsInstalled[] = "ExamplePlugin"
PluginsInstalled[] = "ExampleRssWidget"
PluginsInstalled[] = "ExampleFeedburner"
PluginsInstalled[] = "Provider"
PluginsInstalled[] = "Feedback"
PluginsInstalled[] = "CoreUpdater"
PluginsInstalled[] = "PDFReports"
PluginsInstalled[] = "UserCountryMap"
PluginsInstalled[] = "Live"
PluginsInstalled[] = "DBStats"
PluginsInstalled[] = "SecurityInfo"
PluginsInstalled[] = "Proxy"
PluginsInstalled[] = "CustomVariables"

[Plugins]
Plugins[] = "CorePluginsAdmin"
Plugins[] = "CoreAdminHome"
Plugins[] = "CoreHome"
Plugins[] = "API"
Plugins[] = "Widgetize"
Plugins[] = "LanguagesManager"
Plugins[] = "Actions"
Plugins[] = "Dashboard"
Plugins[] = "MultiSites"
Plugins[] = "Referers"
Plugins[] = "UserSettings"
Plugins[] = "Goals"
Plugins[] = "SEO"
Plugins[] = "UserCountry"
Plugins[] = "VisitsSummary"
Plugins[] = "VisitFrequency"
Plugins[] = "VisitTime"
Plugins[] = "VisitorInterest"
Plugins[] = "ExampleAPI"
Plugins[] = "ExamplePlugin"
Plugins[] = "ExampleRssWidget"
Plugins[] = "ExampleFeedburner"
Plugins[] = "Provider"
Plugins[] = "Feedback"
Plugins[] = "Login"
Plugins[] = "UsersManager"
Plugins[] = "SitesManager"
Plugins[] = "Installation"
Plugins[] = "CoreUpdater"
Plugins[] = "PDFReports"
Plugins[] = "UserCountryMap"
Plugins[] = "Live"
Plugins[] = "DBStats"
Plugins[] = "SecurityInfo"
Plugins[] = "CustomVariables"

[General]
action_url_category_delimiter = "/"
action_title_category_delimiter = "/"
autocomplete_min_sites = 5
site_selector_max_sites = 10
show_multisites_sparklines = 1
action_default_name = "index"
action_default_name_when_not_defined = "page title not defined"
action_default_url_when_not_defined = "page url not defined"
default_language = "en"
datatable_default_limit = 10
API_datatable_default_limit = 50
default_day = "yesterday"
default_period = "day"
time_before_today_archive_considered_outdated = 10
enable_browser_archiving_triggering = 1
minimum_php_version = "5.1.3"
minimum_mysql_version = 4.1
minimum_pgsql_version = 8.3
minimum_memory_limit = 128
force_ssl_login = 0
login_cookie_name = "piwik_auth"
login_cookie_expire = 1209600
login_cookie_path = ""
login_password_recovery_email_address = "password-recovery@{DOMAIN}"
login_password_recovery_email_name = "Piwik"
enable_framed_logins = 0
language_cookie_name = "piwik_lang"
noreply_email_address = "noreply@{DOMAIN}"
feedback_email_address = "hello@piwik.org"
datatable_archiving_maximum_rows_referers = 1000
datatable_archiving_maximum_rows_subtable_referers = 50
datatable_archiving_maximum_rows_actions = 500
datatable_archiving_maximum_rows_subtable_actions = 100
datatable_archiving_maximum_rows_standard = 500
use_ajax_cdn = 0
jquery_version = "1.4.2"
jqueryui_version = "1.8.4"
swfobject_version = 2.2
reverse_proxy = 0
latest_version_url = "http://piwik.org/latest.zip"
api_service_url = "http://api.piwik.org"

